"""empty message

Revision ID: 2f23e4c0cbb9
Revises: 396e6f2c0732
Create Date: 2016-08-07 01:09:42.207857

"""

# revision identifiers, used by Alembic.
revision = '2f23e4c0cbb9'
down_revision = '396e6f2c0732'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(), nullable=True))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text("timezone('UTC'::text, now())"))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text("timezone('UTC'::text, now())"))
    op.drop_column('users', 'email')
    ### end Alembic commands ###
