"""empty message

Revision ID: 3110579f618c
Revises: d99899e9252f
Create Date: 2016-08-07 04:18:29.035112

"""

# revision identifiers, used by Alembic.
revision = '3110579f618c'
down_revision = 'd99899e9252f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_group', sa.Column('created_at', sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP AT TIME ZONE 'UTC')"), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_group', 'created_at')
    ### end Alembic commands ###
