"""empty message

Revision ID: a605af8daf8b
Revises: 5771a854a4d9
Create Date: 2016-08-07 02:04:44.899257

"""

# revision identifiers, used by Alembic.
revision = 'a605af8daf8b'
down_revision = '5771a854a4d9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    ### end Alembic commands ###
