"""empty message

Revision ID: ab2d76c09692
Revises: 3110579f618c
Create Date: 2016-08-07 04:45:52.531366

"""

# revision identifiers, used by Alembic.
revision = 'ab2d76c09692'
down_revision = '3110579f618c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_id_group_id_unique_key', 'user_group', ['user_id', 'group_id'])
    op.drop_constraint('user_group_group_id_key', 'user_group', type_='unique')
    op.drop_constraint('user_group_user_id_key', 'user_group', type_='unique')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_group_user_id_key', 'user_group', ['user_id'])
    op.create_unique_constraint('user_group_group_id_key', 'user_group', ['group_id'])
    op.drop_constraint('user_id_group_id_unique_key', 'user_group', type_='unique')
    ### end Alembic commands ###
